Adding new blog post about windows scanners (PingCastle)
secureCodeBox/documentation pull request #106
Opened 2021-08-09 14:13 UTC by SebieF

I wrote a blog post about my work to integrate PingCastle into the scb. 

Any comments much appreciated :)

2021-08-10 11:48 UTC, Weltraumschaf requested changes
Nice work. I added some minor suggstions and questions.

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +  description: This post describes our journey to integrate a Windows scanner into the scb.
```suggestion
description: This post describes our journey to integrate a Windows scanner into the scb.
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +  image: /img/blog/2021-08-09-windows.jpg
```suggestion
image: /img/blog/2021-08-09-windows.jpg
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +Get some insights into the fascinating and exhausting world of integrating windows scanners into the secureCodeBox.
```suggestion
Get some insights into the fascinating and exhausting world of integrating Microsoft Windows™ scanners into the _secureCodeBox_.
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +While most of the scanners already implemented in the secureCodeBox can target and be run on any operating system,
```suggestion
While most of the scanners already implemented in the _secureCodeBox_ can target and be run on any operating system,
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +It is the first scanner that we went for integrating in the secureCodeBox, and what a journey it was!
```suggestion
It is the first scanner that we went for integrating in the _secureCodeBox_, and what a journey it was, not!
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +As [PingCastle is open source](https://github.com/vletoux/pingcastle), our first attempt was to compile it ourselves
"As PingCaste ..., our first attempt" Is here something missing?

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +little picky as we will see later..
```suggestion
little picky as we will see later...
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +while the machine was connected automatically to the VPN (e.g. using *rasdial*), while it would perfectly do its job
What is rasdial? Maybe a link to some explanatory site is a good idea?

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +capable to be integrated into the secureCodeBox. We already provide you with all other necessary files, especially
```suggestion
capable to be integrated into the _secureCodeBox_. We already provide you with all other necessary files, especially
```

2021-08-10 11:48 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +of time. Maybe the VM will shut down unexpectedly, and we all know and love the blue welcome screen when Windows
```suggestion
of time. Maybe the VM will shut down unexpectedly, and we all know and love the BSoD when Windows
```

2021-08-12 07:46 UTC, SebieF commented on blog/2021-08-09-integrating-windows-scanners.md
> +As [PingCastle is open source](https://github.com/vletoux/pingcastle), our first attempt was to compile it ourselves
As PingCastle is open source, maybe misleading because of the link?

2021-08-17 11:41 UTC, Weltraumschaf commented on blog/2021-08-09-integrating-windows-scanners.md
> +As [PingCastle is open source](https://github.com/vletoux/pingcastle), our first attempt was to compile it ourselves
No idea, now it makes sense to me 🤪

2021-08-17 11:41 UTC, merged