Maintenance/update docs
secureCodeBox/documentation pull request #111
Opened 2021-08-30 12:26 UTC by Ilyesbdlala

Updated documentation in the following locations:
- ParseDefinition: updated the example
- parser (directory): updated the Docker image alpine version 12 -> 14.
-  ScanType: updated the example

2021-09-07 11:47 UTC, SebieF reviewed
Good changes, one addition could be made :)

2021-09-07 11:47 UTC, SebieF commented on docs/contributing/integrating-a-scanner/parser-dir.md
Would be cool to add a note that if your parser does not depend on any additional packages (no package.json file required), a reduced Dockerfile for the parser can be used:
```
ARG namespace

ARG baseImageTag

FROM ${namespace:-securecodebox}/parser-sdk-nodejs:${baseImageTag:-latest}  

WORKDIR /home/app/parser-wrapper/parser/  

COPY --chown=app:app ./parser.js ./parser.js
```

2021-09-08 12:14 UTC, Ilyesbdlala commented on docs/contributing/integrating-a-scanner/parser-dir.md
Yeah that's a good suggession. I added it to the PR.

2021-09-10 05:24 UTC, SebieF approved these changes
:+1:

2021-09-10 08:06 UTC, J12934 requested changes

2021-09-10 08:06 UTC, J12934 commented on docs/api/crds/parse-definition.md
> +    {{- toYaml .Values.parser.env | nindent 4 }}
This example is great for users wanting to integrate new scanners into our repo, but is incorrect in my opinion at this page.
This API page describes the ParseDefinition CRD and which values are supported by it.

The helm templates you changed it to, describe the helm templates we use in our helm charts by convention, but its not required for users to use the same conventions. I'd prever to keep this page focussed on the actual crd and add a note like: "If you are adding new ParseDefinitions to the secureCodeBox repo, see the conventions used for the helm charts of integrated scanner: <link to contributions page." 

This example should then be moved to the contributions page (if it doesn't exist there already)

2021-09-10 10:28 UTC, Ilyesbdlala commented on docs/api/crds/parse-definition.md
> +    {{- toYaml .Values.parser.env | nindent 4 }}
Yeah I agree, I just changed to that way now,

2021-09-13 08:30 UTC, fuhrmeistery approved these changes

2021-09-13 08:36 UTC, merged