Blogpost: How we work (closes #112)
secureCodeBox/documentation pull request #113
Opened 2021-09-07 11:35 UTC by SebieF

To engage further community interaction, we decided to write a blog post about how our core development team works. 

(closes #112)

2021-09-10 11:26 UTC, Weltraumschaf requested changes
Nice work! I've added some minor suggestions.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +title: How our core development team works
```suggestion
title: How Our Core Development Team Works
```

See https://titlecaseconverter.com/

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +author_title: Contributor
```suggestion
author_title: Core Developer
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +The _secureCodeBox_ is still a small, yet growing open source project. At the moment, the major share of work is done
```suggestion
The _secureCodeBox_ is still a small, yet growing open source project. At the time of writing, the major share of work is done
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +by roundabout 8 developers from [Iteratec](https://iteratec.com).
```suggestion
by roundabout eight developers from [Iteratec](https://iteratec.com).
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +That's also where the idea for the _scb_ was born about 4 years ago.
```suggestion
That's also where the idea for the _secureCodeBox_ was born about 4 years ago. 
```

Better for marketing reasons so that the name oft the greatest scanner burns into the brains ;-)

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +Both, students and full-time developers, work together in our team. This, of course, requires some coordination,
We should also mention that we are geographically highly distributed.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +[SCRUM](https://www.scrum.org/resources/what-is-scrum) and [KANBAN](https://en.wikipedia.org/wiki/Kanban_(development)).
Neither Scrum nor Kanban are acronyms ;-)

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +That's why we are working in an *agile* setup and try to stick to the general ideas of
```suggestion
That's why we are working in an _agile_ setup and try to stick to the general ideas of 
```

Always use one style of syntax in a single file. Above you used underscore for emphasis.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +We work in **sprints** of 2 weeks (regularly). For each sprint, our Product Owner (PO) decides, which tasks are the most
```suggestion
We work in **sprints** of two weeks (regularly). For each sprint, our Product Owner (PO) decides, which tasks are the most
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +"tickets" are publicly available on GitHub as [Issues](https://github.com/secureCodeBox/secureCodeBox/issues).
```suggestion
tickets are publicly available on GitHub as [issues](https://github.com/secureCodeBox/secureCodeBox/issues). 
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +The issues in the *To-Do* column are sorted by their importance regarding the current sprint.
```suggestion
The issues in the _To-Do_ column are sorted by their importance regarding the current sprint.
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +For each issue, a developer (team) will usually create a new branch in the repository and commit its changes there.
```suggestion
For each issue, one or more developers will usually create a new branch in the repository and commit its changes there.
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +our ci tests and the reviewer are satisfied, the PR gets merged by one of our admins.
```suggestion
our CI tests and the reviewer are satisfied, the PR gets merged by automatically or by one of our admins.
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +The highlight of every sprint, finally, is our *Review/Retro/Planning* session. It lasts about 2 hours, while we first
```suggestion
The highlight of every sprint, finally, is our *Review/Retro/Planning* session. It lasts about two hours, while we first
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +**review** which results we could achieve during the last sprint, i.e. which issues we worked on. We often show
```suggestion
**review** which results we've achieved during the last sprint, i.e. which issues we worked on. We often show
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +new features that we added to the other developers and the product owner, or point out on problems that we are
```suggestion
new features that we added to the other developers and the Product Owner, or point out on problems that we are 
```

Above you wrote it as a proper noun.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +consequences.
We should point out the very important aspect of inspect and adapt which is the core philosophy of our agile mindset in the team.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +
We should also add some words about the fact that two hours for such a meeting is very short and the constraints we're facing.

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +## How we work
```suggestion
## How We Work
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +## Get engaged!
```suggestion
## Get Engaged!
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +That's basically it. You now know how our core development team is organized to work at the _secureCodeBox_.
"That's basically it." Sounds strange to me. 🤔

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +If you are a regular user of the _scb_ and/or want to contribute more actively to the code, now is the best time to start!
```suggestion
If you are a regular user of the _secureCodeBox_ and/or want to contribute more actively to the code, now is the best time to start!
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +or joining our [slack channel](https://join.slack.com/t/securecodebox/shared_invite/enQtNDU3MTUyOTM0NTMwLTBjOWRjNjVkNGEyMjQ0ZGMyNDdlYTQxYWQ4MzNiNGY3MDMxNThkZjJmMzY2NDRhMTk3ZWM3OWFkYmY1YzUxNTU%22).
```suggestion
or joining our [Slack channel](https://join.slack.com/t/securecodebox/shared_invite/enQtNDU3MTUyOTM0NTMwLTBjOWRjNjVkNGEyMjQ0ZGMyNDdlYTQxYWQ4MzNiNGY3MDMxNThkZjJmMzY2NDRhMTk3ZWM3OWFkYmY1YzUxNTU%22).
```

2021-09-10 11:26 UTC, Weltraumschaf commented on blog/2021-09-07-how-we-work.md
> +We are happy to hear from you and discuss, how we can get you involved into our development process!
Maybe we should add some words about our idea to do the review and/or planning in the public and also some words about the problems: More time necessary, time zones etc.

2021-09-14 11:19 UTC, SebieF commented on blog/2021-09-07-how-we-work.md
> +
I added the time constraint to the final section

2021-09-14 12:41 UTC, Weltraumschaf approved these changes

2021-09-14 12:41 UTC, merged