Scope limiter documentation
secureCodeBox/documentation pull request #155
Opened 2021-11-17 17:42 UTC by EndPositive

This PR accompanies secureCodeBox/secureCodeBox#805.

* Updates CRD for `scopeLimiter` and `scopeLimiterAliases` 
* Adds HowTo for enforcing scope on an engagement
* Updates `values.yaml` doc for new scanners

2021-11-18 08:31 UTC, malexmave requested changes
Thanks for the documentation. I have a few, mostly small, requests and suggestions, but this is already looking quite good.

2021-11-18 08:31 UTC, malexmave commented on docs/api/crds/scan.md
> +like this:
What is this sentence doing here? Looks like a leftover.

2021-11-18 08:31 UTC, malexmave commented on docs/api/crds/scan.md
>  To use cascades you'll need to have the [CombinedScan hook](https://docs.securecodebox.io/docs/hooks/cascading-scans) installed.
```suggestion
To use cascades you'll need to have the [CascadingScan hook](https://docs.securecodebox.io/docs/hooks/cascading-scans) installed.
```

Once again spotting things that aren't related to your changes but should be fixed :).

2021-11-18 08:31 UTC, malexmave commented on docs/api/crds/scan.md
> +For example, you can define that you can only cascade on a host, if the found ip address is within your predefined ip range.
```suggestion
For example, you can define that you can only trigger a follow-up scan against a host if its IP address is within your predefined IP range.
```

2021-11-18 08:31 UTC, malexmave commented on docs/api/crds/scan.md
> +Specifying a scope annotation in [`scanAnnotations`](/docs/api/crds/cascading-rule#scanlabels--scanannotations-optional) is not allowed.
```suggestion
These annotations can only be added on the initial scan (i.e., they cannot be modified using the [`scanAnnotations`](/docs/api/crds/cascading-rule#scanlabels--scanannotations-optional) field of the cascading scan rules) and are inherited by default.
```

2021-11-18 08:31 UTC, malexmave commented on docs/api/crds/scan.md
> +`operator` is one of  `In`, `NotIn`, `Exists`, `DoesNotExist`, `Contains`, `DoesNotContain`, `InCIDR`, `NotInCIDR`, `SubdomainOf`, `NotSubdomainOf`.
Do you explain anywhere what these do? If not, this would be helpful as maybe not everyone knows what a CIDR is, or (for example) if `google.com SubdomainOf google.com` should be expected to return true or false (does it strictly match only subdomains, or also the domain itself). Can you add a few sentences for each that is not part of the standard kubernetes selectors, and ideally link the others to the k8s docs that explain how they work (assuming your implementation works the same way)? This does not necessarily have to be explained in this exact location (but if you explain it somewhere else, like in the howto article, you should link it from here).

2021-11-18 08:31 UTC, malexmave commented on docs/how-tos/scope.md
> +In the cascading scans logs, you will see that lot's of rules were not triggered as the domain was out of scope.
```suggestion
In the cascading scans logs, you will see that lots of rules were not triggered as the domain was out of scope.
```

2021-11-18 08:31 UTC, malexmave commented on docs/how-tos/scope.md
> +$ k
This is probably not the correct command?

2021-11-18 17:10 UTC, EndPositive commented on docs/api/crds/scan.md
> +like this:
ff6edc2e

2021-11-18 17:10 UTC, EndPositive commented on docs/how-tos/scope.md
> +$ k
ff6edc2e

2021-11-18 18:00 UTC, EndPositive commented on docs/api/crds/scan.md
> +`operator` is one of  `In`, `NotIn`, `Exists`, `DoesNotExist`, `Contains`, `DoesNotContain`, `InCIDR`, `NotInCIDR`, `SubdomainOf`, `NotSubdomainOf`.
a869ff52 Add documentation for each scope limiter operator type

Didn't add link to existing docs as they are also quite confusing and contain lots of information about unrelated features. Here's a link if you'd like to take a look yourself: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements

2021-11-19 07:14 UTC, malexmave commented on docs/api/crds/scan.md
> +`operator` is one of  `In`, `NotIn`, `Exists`, `DoesNotExist`, `Contains`, `DoesNotContain`, `InCIDR`, `NotInCIDR`, `SubdomainOf`, `NotSubdomainOf`.
Okay, that looks fine, thank you :).

2021-11-26 12:16 UTC, malexmave commented on docs/api/crds/scan.md
> +values: ["{{#list}}{{attributes.domains}}{{/list}}"]
Hm, this is a different example from the one we discussed, and at least in my unit tests, it does not work (templating fails if you try to run it like that).

The example that should work is this finding: 
```json
{
  "name": "subdomain.domain.tld",
  "domain": "domain.tld",
  "addresses": [
    {
      "ip": "11.22.33.44",
    },
    {
      "ip": "2a01:fefe::1",
    }
  ],
}
```
With the limiter:
```yaml
annotations:
  scope.cascading.securecodebox.io/cidr4: "11.22.0.0/16"
  scope.cascading.securecodebox.io/cidr6: "2a01:fefe::/31"
...
scopeLimiter:
  allOf:
  - key: "scope.cascading.securecodebox.io/cidr4"
    operator: "InCIDR"
    values: ["{{#list}}attributes.addresses.ip{{/list}}"]
  - key: "scope.cascading.securecodebox.io/cidr6"
    operator: "InCIDR"
    values: ["{{#list}}attributes.addresses.ip{{/list}}"]
```

However, I think the example you are giving may be a valid use case that we should support somehow (at least I cannot get it to work with any of the syntax we have so far).

I would propose doing both: adding support for what you describe here to the code, and adding the stuff that we are already supporting to the documentation so that people know how to use it for amass results, for example.

2021-11-26 12:23 UTC, EndPositive commented on docs/api/crds/scan.md
> +values: ["{{#list}}{{attributes.domains}}{{/list}}"]
I'll take another look at this. Do you still have complete example amass findings?

2021-11-26 12:25 UTC, malexmave commented on docs/api/crds/scan.md
> +values: ["{{#list}}{{attributes.domains}}{{/list}}"]
I'll send it to you on slack - but Amass findings work with the current version of the PR, it's the syntax you use here that does not. I am not sure if the one from your version of the docs is even used by any scanner, but I think it's good to support it.

2021-11-26 13:52 UTC, EndPositive commented on docs/api/crds/scan.md
> +values: ["{{#list}}{{attributes.domains}}{{/list}}"]
I've added a failing test for this. I should have tested this example before, but didn't see how it would be different. It comes down to the fact that mustache handles list of strings differently than list of objects: https://github.com/janl/mustache.js/#non-empty-lists.

We can update our list function to support both. Ideally they should have the same scb syntax.

2021-11-29 14:49 UTC, EndPositive commented on docs/api/crds/scan.md
> +values: ["{{#list}}{{attributes.domains}}{{/list}}"]
Test fix and examples have been added.

2021-11-30 17:25 UTC, malexmave approved these changes

2021-11-30 17:27 UTC, malexmave commented
Leaving this unmerged until the release with the feature is published, but this should be ready to go.

2021-12-08 15:13 UTC, merged