Add instructions for building scanners and hooks locally
secureCodeBox/documentation pull request #156
Opened 2021-11-18 16:57 UTC by EndPositive

This PR adds an document that explains how to build scanners/hooks for a local Kubernetes instance.
There is a section for using the Makefiles and manually building.
There's instructions for Minikube and KinD to load the images into a cluster.
And there's a section for debugging. Feel free to add more :smile:.

2021-11-19 07:23 UTC, malexmave requested changes
Thanks for this PR, this will be very helpful for the documentation, I think. I have some small requests and questions, but think that they should be rather quick to address.

2021-11-19 07:23 UTC, malexmave commented on docs/contributing/local-deployment.md
> +4. Run `make deploy` to install your Helm chart into your active Kubernetes cluster.
By default, this deploys into the `integration-tests` namespace, not the currently active one. We should explicitly state that (or change the Makefile to make it easier to change this namespace and document *that* 😁 ).

2021-11-19 07:23 UTC, malexmave commented on docs/contributing/local-deployment.md
> +## Manual build & deploy
Is there any particular reason why we would document how to do manually what we want people to do using the Makefile? In which situation would it not be possible / a good idea to use the Makefile? Just asking because if we ever change the build process in the Makefiles, this section is additional work to maintain and I don't really see the benefit right now.

2021-11-19 07:23 UTC, malexmave commented on docs/contributing/local-deployment.md
> +Check with `kubectl describe pod scan-nmap-n6jpg--1-gxnhp` which image your scanner wants to use and whether you have made that image available.
The name is probably not correct.
```suggestion
Check with `kubectl describe pod [name of pod]` which image your scanner wants to use and whether you have made that image available.
```

2021-11-19 07:23 UTC, malexmave commented on docs/contributing/local-deployment.md
> +  * Manually: `kind load docker-image parser-nmap:sha-a4490167`.
The SHA will most likely also not be correct. Also see the concerns about manual vs. Makefile above.

2021-11-19 10:32 UTC, EndPositive commented on docs/contributing/local-deployment.md
> +## Manual build & deploy
I'm confident that describing manual deployment is helpful for learning and debugging purposes. It outlines clearly what Docker images/tags are retrieved from where and which build arguments are used. The Makefiles can be a bit of a black box, especially for newcomers. If there are any build issues, it can be unclear from the Makefiles what is wrong/missing. I don't think we'll update the build/deploy process anytime soon, so I expect it won't be a maintainability chore.

2021-11-19 10:42 UTC, EndPositive commented on docs/contributing/local-deployment.md
> +4. Run `make deploy` to install your Helm chart into your active Kubernetes cluster.
8f553984 - Clarify deploy namespace

We can update Makefile deployment namespace in the future :grin:

2021-11-19 10:45 UTC, EndPositive commented on docs/contributing/local-deployment.md
> +Check with `kubectl describe pod scan-nmap-n6jpg--1-gxnhp` which image your scanner wants to use and whether you have made that image available.
a03a4ac5 - Use placeholders for dynamic tags/names

2021-11-19 10:46 UTC, EndPositive commented on docs/contributing/local-deployment.md
> +  * Manually: `kind load docker-image parser-nmap:sha-a4490167`.
a03a4ac5 - Use placeholders for dynamic tags/names

2021-11-22 09:16 UTC, malexmave approved these changes

2021-11-22 09:17 UTC, malexmave commented
Thanks for the poke, I had forgotten about this PR. Looks good to me, merging it now :).

2021-11-22 09:17 UTC, merged