Autogenerate Sidebar
secureCodeBox/documentation pull request #206
Opened 2021-12-28 15:27 UTC by RamiSouai

Closes #92 

- Instead of specifing every filename for the doc pages in config.js, we let Docusaurus  generate the sidebar based on the files in the directory after getting the docs from the main respository.
- The sidebar objects appear alphabetically per default, unless a sidebar_position attribute is provided in the respective file https://docusaurus.io/docs/sidebar#autogenerated-sidebar-metadata
- Subdirectories now have a _category_.json file specifying the sidebar label und position of the repective category
- the adr (Architecture decision records) directory is a special case, since it is deleted during the build. The build script was modified to only remove md files

2022-02-09 10:21 UTC, Weltraumschaf requested changes
I like tha tyou use a Markdown linter 🤗

In general you should do formatting in a separate PR because reformatting done bey an formatter may be easier and faster reviewed, if I do not have to spot logic changes inside the diffs.

Also updates of dependencies shouldbe in a separate PR so we can deploy the formatting and logic chenges separately, if thedependency updates break something, unless the dependnecies are necessary for the logic changes.

> the adr (Architecture decision records) directory is a special case, since it is deleted during the build. The build script was modified to only remove md files

Should we also delete the hooks and scanner Markdown files, too? Because if we remove a scanner/hook the file will be stale in the direcotry.

2022-02-09 10:21 UTC, Weltraumschaf commented on docs/api/crds/scan-completion-hook.md
> +    - name: ELASTICSEARCH_ADDRESS
What happened here? Tabs vs spaces?

2022-02-09 10:21 UTC, Weltraumschaf commented on docs/contributing/integrating-a-hook/hook.md
> -If you make changes to some findings you will have to call `updateFindings()` with ***ALL*** findings not just with the ones that have changed or unchanged findings will get lost!
From typography perspective emphasise and strong should be used very rare. General advice is: Use strong for important things and emphasise (italic) for special (named) things (e.g. SCB specific wording like _scanner_ to signal that in our text a scanner is something special in SCB and does not mean scanner at all).

2022-02-09 10:21 UTC, Weltraumschaf commented on docs/contributing/integrating-a-hook/templates-dir.md
> +  ttlSecondsAfterFinished: { { .Values.hook.ttlSecondsAfterFinished } }
Is this a typo? Shold there be a space between the two curly braces?

2022-02-09 10:21 UTC, Weltraumschaf commented on scripts/docs.build.js
> +  const fullRepoName = config.repository + `#` + config.branch;
Why use backticks in combiantion with string concat? AFAIK they are interplated. So for me two options make more sense:

1. `const fullRepoName = config.repository + '#' + config.branch;`
2. ``const fullRepoName = `config.repository#config.branch;` ``

2022-02-09 10:21 UTC, Weltraumschaf commented on scripts/docs.build.js
> +      ? await createDocFilesFromDir(srcDir, trgDir, await readDirectory(srcDir))
Are they generated in the main repo? If so, this should be reflected in the function name, so that everyone know that you ferst have to checkout that repo to do this.

2022-02-21 18:12 UTC, RamiSouai commented on docs/api/crds/cascading-rule.md
> +    mynewlabel: { { metadata.name } }
Leading spaces after curly brackets caused by the linter. Doesn't effect functioanlity, just code aesthetic.

2022-02-21 19:09 UTC, RamiSouai commented on docs/api/crds/scan-completion-hook.md
> +    - name: ELASTICSEARCH_ADDRESS
Linter was configured with a different size tab

2022-02-21 19:23 UTC, RamiSouai commented on scripts/docs.build.js
> +      ? await createDocFilesFromDir(srcDir, trgDir, await readDirectory(srcDir))
> In general you should do formatting in a separate PR because reformatting done bey an formatter may be easier and faster reviewed, if I do not have to spot logic changes inside the diffs.

Noted, will do for next PRs. 😄 

> Also updates of dependencies shouldbe in a separate PR so we can deploy the formatting and logic chenges separately, if thedependency updates break something, unless the dependnecies are necessary for the logic changes.

This dependency update was necessary since the category overview page is only available since a more recent docusaurus version

> > the adr (Architecture decision records) directory is a special case, since it is deleted during the build. The build script was modified to only remove md files
> 
> Should we also delete the hooks and scanner Markdown files, too? Because if we remove a scanner/hook the file will be stale in the direcotry.

Yes, I should have specified this. Removing only md files (instead of the entire directory) applies to all imported directories ([Can be seen here](https://github.com/secureCodeBox/documentation/pull/206/files#diff-2649b69a6dd1ad37037be6c189f107d410af991f16e57a3630ca7c0399ebfa52L60))

2022-02-21 19:24 UTC, RamiSouai commented
> In general you should do formatting in a separate PR because reformatting done bey an formatter may be easier and faster reviewed, if I do not have to spot logic changes inside the diffs.

Noted, will do for next PRs. 😄 

> Also updates of dependencies shouldbe in a separate PR so we can deploy the formatting and logic chenges separately, if thedependency updates break something, unless the dependnecies are necessary for the logic changes.

This dependency update was necessary since the category overview page is only available since a more recent docusaurus version

> > the adr (Architecture decision records) directory is a special case, since it is deleted during the build. The build script was modified to only remove md files
> 
> Should we also delete the hooks and scanner Markdown files, too? Because if we remove a scanner/hook the file will be stale in the direcotry.

Yes, I should have specified this. Removing only md files (instead of the entire directory) applies to all imported directories ([Can be seen here](https://github.com/secureCodeBox/documentation/pull/206/files#diff-2649b69a6dd1ad37037be6c189f107d410af991f16e57a3630ca7c0399ebfa52L60))

2022-02-22 09:54 UTC, Weltraumschaf commented on docs/api/crds/cascading-rule.md
> +    mynewlabel: { { metadata.name } }
It's not just code aesthetic. It violates the principle of least astonishment because in all our other templates (Helm charts and such) we use the syntax `{{` and `}}`. In fact I never seen this format before. So this will confuse novice developers. We should do this consistent in our whole code base. So, if there is no good reason why the space between the braces (`{ {`) has any advantage over the usual format ('{{') we should stick to the usual format without the space between the braces. In fact: You must not use any new formatting rules which are not discussed and approved by the team and we can guaranty that any contributor uses the same formatter e.g. by adding the install instruction and config into the repo.

2022-02-22 09:56 UTC, Weltraumschaf commented on docs/api/crds/scan-completion-hook.md
> +    - name: ELASTICSEARCH_ADDRESS
Pleas stick to the origin format. We do not have a rigid formatter guideline at the moment. But it is no good to format small parts of a code base differently than the rest, even less with a syntax which has significant whitespaces like Markdown or YAML.

2022-02-22 09:57 UTC, RamiSouai commented on docs/api/crds/cascading-rule.md
> +    mynewlabel: { { metadata.name } }
I see, will remove

2022-02-22 10:35 UTC, Weltraumschaf reviewed
LGTM, but see open disscussions.

2022-03-01 15:41 UTC, Weltraumschaf approved these changes

2022-03-08 11:03 UTC, merged