initial commit
secureCodeBox/documentation pull request #211
Opened 2022-01-20 10:56 UTC by Stijn-FE

Signed-off-by: Stijn van Es <stijn.vanes@secura.com>

2022-01-28 08:40 UTC, J12934 reviewed
Hi awesome work.
Really like the structure of the templates, this should really expand the doc to include aspects previously grossly uncovered by it.

I've tried to answered @EndPositive questions in the issue as much as possible, hope this helps.

I've added a suggestion to update the iteratec team members and their roles.

What tool did you use to generate the diagrams? Would it be possible to include their source files in the repo so that they stay editable? Otherwise we'd have to completely redraw them whenever we want to change them.

2022-01-28 09:05 UTC, Stijn-FE commented
Hi, happy to hear the structure is to your liking. 

Thanks for the info and the additional changes. 

For the diagrams, I've used [draw.io](https://app.diagrams.net/). The source code is incorporated in the `.png` files. You should be able to load the `.png` files directly into the draw.io editor. I'll add an explanation on how to edit in the docs.

2022-03-11 10:45 UTC, Weltraumschaf commented
Hi @Stijn-FE ,

we have decided to start documenting the architecture. The idea is as follows:

1. I review what you've done yet.
2. We merge your PR.
3. I refactor your work to match the [Arc42](https://arc42.org/) template. (This is a widely adopted template for architecture documentation.)
4. Then we evolve the documentation step-by-step.

So, please convert your PR from `draft` to `ready` :-)

If you're not familiar with Arc42 and want to know more about it, we may schedule a short (~30 min) appointment to tell you the basic idea of it.

2022-03-11 13:01 UTC, Stijn-FE commented
Hi Sven, 

Good idea to use Arc42. I looked into this a while ago and actually meant to use this template in this PR. If you have any questions regarding the changes in this PR, please let me know.

2022-03-11 13:23 UTC, Weltraumschaf commented
Ah, I wondered if you did the structure by accident like Arc42 :-)

2022-03-11 13:53 UTC, Weltraumschaf requested changes
Nice work! This is a really good starting point and my hope is that we now evolve to a good architecture doc with this foundation :-)

If you do my suggestions (mostly the copyright header) I'll merge this.

2022-03-11 13:53 UTC, Weltraumschaf commented on docs/architecture/introduction.md
> +This document describes the secureCodeBox Project (SCB) and is based on the [arc42](https://arc42.org/overview/) architecture documentation template. SecureCodeBox is a Kubernetes based, modularized
Ah, you didn't match the Arc42 structure by accident 👍

2022-03-15 08:16 UTC, Weltraumschaf commented
Hi @Stijn-FE,

would you please look into our suggested changes? Our current sprint ends tomorrow and we would like to merge this PR to plan the next steps for the next sprint.

2022-03-16 09:38 UTC, EndPositive commented
Leaving a comment here that Stijn is currently unavailable, but verbally agreed to the last few comments.

2022-03-16 09:39 UTC, Weltraumschaf commented on docs/architecture/technical/building-block-view.md
> +Below, an overview is given of the global design/architecture of secureCodeBox. This document is inspired by the [C4](https://c4model.com/) model for visualizing software architecture. Conform this m
@EndPositive Maybe you can answer this: Is this a copy & paste error or why Django?

2022-03-16 09:40 UTC, Weltraumschaf commented
Hi @Stijn-FE,

@EndPositive told me that you're away at the moment, so I committed all the suggestions and will merge it.

2022-03-16 09:43 UTC, EndPositive commented on docs/architecture/technical/building-block-view.md
> +Below, an overview is given of the global design/architecture of secureCodeBox. This document is inspired by the [C4](https://c4model.com/) model for visualizing software architecture. Conform this m
Hi Sven, this is indeed a copy paste error. You may remove the text in between brackets and the text looks valid to me.

2022-03-16 10:18 UTC, Weltraumschaf commented on docs/architecture/technical/building-block-view.md
> +Below, an overview is given of the global design/architecture of secureCodeBox. This document is inspired by the [C4](https://c4model.com/) model for visualizing software architecture. Conform this m
```suggestion
Below, an overview is given of the global design/architecture of secureCodeBox. This document is inspired by the [C4](https://c4model.com/) model for visualizing software architecture. Conform this model, this document is split in 4 parts (i.e. levels). First, a `context` level overview, displaying the context in which the application is used. The second level, `containers`, broadly describes the different data streams. The third level consists of a `components` overview, describing the different components and the interactions between them. The fourth and final level contains a `code` overview. Which will consist of class- and database-diagrams.
```

2022-03-16 10:19 UTC, Weltraumschaf commented on docs/architecture/technical/building-block-view.md
> +Below, an overview is given of the global design/architecture of secureCodeBox. This document is inspired by the [C4](https://c4model.com/) model for visualizing software architecture. Conform this m
Also replaced apps w/ components. It's not a good sentence, but we do not have "apps" and this text will undergo heavy rewriting in the next months anyway, when we evolve the architecture doc.

2022-03-16 10:20 UTC, Weltraumschaf approved these changes

2022-03-16 10:20 UTC, merged