Article about sundown and EOL of version 1
secureCodeBox/documentation pull request #24
Opened 2020-10-13 13:47 UTC by Weltraumschaf

Signed-off-by: Sven Strittmatter <Sven.Strittmatter@iteratec.com>

2020-10-13 14:44 UTC, J12934 requested changes

2020-10-13 14:44 UTC, J12934 commented on blog/2020-10-15-sundown-and-eol-of-version-1.md
> +Sad news but the _secureCodeBox_ version 1 will  soon reach its end of life. So here we announce its sundown phase beginning from now on until the end of the year.
```suggestion
Sad news but the _secureCodeBox_ version 1 will soon reach its end of life. So here we announce its sundown phase beginning from now on until the end of the year.
```

2020-10-13 14:44 UTC, J12934 commented on blog/2020-10-15-sundown-and-eol-of-version-1.md
> +So you may face a major fuckup now. We understand that such a move is almost always quite a bit badass. That's why we ask you for sorry and hope we won't lose you as a *secureCodeBox* user. If you ne
"badass" is a weird word and doesn't really make sense to me in this context.
Did you mean something like "a pain in the ass"? I'd just use a word like annoying.

2020-10-13 14:53 UTC, Weltraumschaf commented on blog/2020-10-15-sundown-and-eol-of-version-1.md
> +From today we announce the sundown phase of _secureCodeBox_ version 1. This means that we will **not implement any new features nor we update any dependencies** in this version! We will only patch cr
Ah, no. The "we" must be deleted here: "**not implement any new features nor update any dependencies**"

2020-10-14 09:46 UTC, J12934 approved these changes

2020-10-14 10:57 UTC, rseedorff approved these changes

2020-10-14 11:05 UTC, merged