Issue 21 context boundary
secureCodeBox/documentation pull request #240
Opened 2022-03-21 13:26 UTC by Weltraumschaf

2022-03-23 12:43 UTC, Weltraumschaf commented
@malexmave I added some more stuff. I'm a little bit stuck on the building block view. IMHO we should do a short meeting next week to discuss the building blocks.

For the moment I think a "syntactical review" is sufficient. For the over all consistency we should do a architecture review w/ some core developer to discuss the chapters.

2022-04-05 10:36 UTC, malexmave commented
<img width="1161" alt="grafik" src="https://user-images.githubusercontent.com/1688580/161735961-fe8ab5e9-f185-4f0b-adf4-7b06cf998d3d.png">

Can you double-check the links and fix the broken ones? I am not sure what the new URL scheme looks like.

2022-04-05 12:15 UTC, malexmave requested changes
@Weltraumschaf I have made some style and grammar fixes and pushed them to this branch, please check if you are fine with them.

Please ensure that the project builds by fixing the ADR links in the blog post (see the previous comment). Other than that, I only have one question, seen as a comment below.

2022-04-05 12:15 UTC, malexmave commented on docs/architecture/07_deployment_view.md
> +Cluster internal security scans directly in the business service's namespace. Only the _engine_ (_operator_, _lurker_, _hooks_) are deployed in a central dedicated namespace. The _Scan Types_ are dep
> Only the _engine_ (_operator_, _lurker_, _hooks_) are deployed in a central dedicated namespace.

Is this correct? I thought hooks are also installed into the sub-namespaces, and only the operator (and potentially lurker) are installed globally?

2022-04-05 15:32 UTC, Weltraumschaf commented on docs/architecture/07_deployment_view.md
> +Cluster internal security scans directly in the business service's namespace. Only the _engine_ (_operator_, _lurker_, _hooks_) are deployed in a central dedicated namespace. The _Scan Types_ are dep
Yes, I'm pretty sure, but this is something we should review with jannik.robert.

About the ADR links: Of course. I wonder why it built on my machine...

2022-04-05 15:39 UTC, malexmave commented on docs/architecture/07_deployment_view.md
> +Cluster internal security scans directly in the business service's namespace. Only the _engine_ (_operator_, _lurker_, _hooks_) are deployed in a central dedicated namespace. The _Scan Types_ are dep
Even easier: I checked our own internal scan git, we install hooks in the individual namespaces.

2022-04-07 10:25 UTC, malexmave approved these changes

2022-04-07 10:40 UTC, merged