Adding missing images for new scanner
secureCodeBox/documentation pull request #247
Opened 2022-03-31 09:06 UTC by rseedorff

2022-04-01 07:26 UTC, Weltraumschaf requested changes

2022-04-01 07:26 UTC, Weltraumschaf commented on static/img/integrationIcons/ZAP Advanced.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M8 24l2.674-9h-9.674l16-15-2.674 9h8.674l-15 15zm-1.586-11h6.912l-1.326 4 5.739-6h-6.065l1.304-4-6.564 6z"/
In the blog and docs we always use kebab-case for image filenames (kebab-case-is-like-this.txt). So, for consistencies sake we should also do this for the scanner images.

2022-04-01 13:17 UTC, rseedorff commented on static/img/integrationIcons/ZAP Advanced.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M8 24l2.674-9h-9.674l16-15-2.674 9h8.674l-15 15zm-1.586-11h6.912l-1.326 4 5.739-6h-6.065l1.304-4-6.564 6z"/
All other images are also in different case, because the name is generated automatically based on the title in the corresponding readme.md file. If the name is not equal it might not work 🤔

2022-04-04 09:55 UTC, Weltraumschaf commented on static/img/integrationIcons/ZAP Advanced.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M8 24l2.674-9h-9.674l16-15-2.674 9h8.674l-15 15zm-1.586-11h6.912l-1.326 4 5.739-6h-6.065l1.304-4-6.564 6z"/
That's not so nice that we do this differently. Also it is not so good, that it is not obvious in this repo that the names are generated.

2022-05-11 13:24 UTC, Weltraumschaf reviewed
I don't like this inconsistent solution, but don't wanna block it.

2022-05-11 13:24 UTC, merged