Uninstallation Documentation
secureCodeBox/documentation pull request #25
Opened 2020-10-14 13:30 UTC by fuhrmeistery

- Add Uninstallation Page
- Include Uninstallation Page in Sidebar

2020-10-14 16:15 UTC, Weltraumschaf requested changes

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +To uninstall the operator it is not enough to delete the operator via `helm` because the operator creates Roles, ServiceAccounts  and RoleBindings used by parsers, lurcher and hooks in every namespac
```suggestion
To uninstall the operator it is not enough to delete the operator via `helm` because the operator creates Roles, ServiceAccounts  and RoleBindings used by parsers, lurchers and hooks in every namespace where scanners and hooks are executed. These cannot be uninstalled via helm because they cannot be referenced via Kubernetes OwnReferences.
```

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +First delete the namespace for the operator
```suggestion
First delete the namespace for the operator:
```

You say first, and then? Is something missing here?

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +```bash {1}
What does `{1}` mean here and why a space before it? Above there was no space.

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +```bash {1}
See above.

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +To delete these CRDs you can execute the following command:
You should insert a line break here.

2020-10-14 16:15 UTC, Weltraumschaf commented on docs/getting-started/uninstallation.md
> +```bash {1}
See above.

2020-10-15 07:09 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +```bash{1}
https://v2.docusaurus.io/docs/markdown-features#line-highlighting

2020-10-15 07:11 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +To uninstall the operator it is not enough to delete the operator via `helm` because the operator creates Roles, ServiceAccounts  and RoleBindings used by parsers, lurcher and hooks in every namespac
Should also be OwnerReferences not OwnReferences

2020-10-15 07:14 UTC, J12934 commented on src/pages/index.js
> +            <Link
I wouldn't put this on the start page, as uninstallation really isn't one of the first things  a user would do. I think it's totally fine to just have it linked in the sidebar.

2020-10-15 07:16 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +Some Resources like the ELK-Stack require a persistent volume.
The more modern name is "elastic stack".

2020-10-15 07:33 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +kubectl get pv
It would be better in this case to delete the elasticsearch "PVC" not the "PV" 

Kubernetes has a interesting divide when it comes to storage.
There are PersistentVolumes (PV, Cluster Scoped) and PersistentVolumesClaims (PVC, Namespaced). PVC are a way for users without cluster rights to request the cluster scoped PV for them.

2020-10-15 07:41 UTC, J12934 requested changes

2020-10-15 07:41 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +## Delete Volumes
This section is duplicated

2020-10-15 07:41 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +# Uninstall Scanners and Hooks
Its best in these doc pages to start with h2 headings, as the h1 heading is automatically generated by docusaurus using the pages titel

2020-10-15 07:41 UTC, J12934 commented on docs/getting-started/uninstallation.md
> +# Uninstall Scanners and Hooks
Otherwise the right sidebar is also pretty messed up as it only shown headings starting at h2

2020-10-19 06:55 UTC, fuhrmeistery commented on docs/getting-started/uninstallation.md
> +```bash {1}
This means the first line will be highlighted

2020-10-19 07:58 UTC, J12934 approved these changes

2020-10-19 08:02 UTC, merged