Documented Introduction and Guideline to the Test Concept
secureCodeBox/documentation pull request #259
Opened 2022-06-02 15:00 UTC by Ilyesbdlala

Related to #71

2022-06-08 14:57 UTC, Ilyesbdlala commented
I am currently debugging why the npm build for our documentation website is currently failing.

2022-06-23 13:06 UTC, the-simmon requested changes

2022-06-23 13:06 UTC, the-simmon commented on docs/contributing/test-concept/index.md
> +For that, we refer to the Martin Fowler article [here](https://martinfowler.com/articles/practical-test-pyramid.html) that presents the fundamentals on creating a good testing pyramid. In a testing p
I would remove the _here_ and move the link to _article_.  

> we refer to the Martin Fowler [article](https://martinfowler.com/articles/practical-test-pyramid.html) that presents the fundamentals

2022-06-23 13:06 UTC, the-simmon commented on docs/contributing/test-concept/index.md
> +We present here how the testing pyramid looks in our case:
This sounds a bit weird. I would just write: _This is the testing pyramid for the SecureCodeBox_

2022-06-23 13:06 UTC, the-simmon commented on docs/contributing/test-concept/index.md
> +We run unit tests to our different SCB modules (e.g. Operator, Hook, Scanner ...). These tests are meant to be fast. For our integration test, we run a complete SCB scan in a Kind Cluster and we eval
_We have unit tests for the different SCB modules_

2022-06-23 13:06 UTC, the-simmon commented on docs/contributing/test-concept/index.md
> +We go over here how each module implements unit and integration tests:
_The following articles describe how each module implements its unit and integration tests:_

2022-06-28 19:06 UTC, the-simmon approved these changes

2022-06-28 19:07 UTC, merged