:books: Adding a persistence storage tutorial
secureCodeBox/documentation pull request #277
Opened 2022-09-19 08:38 UTC by SebieF

Once applied, this PR adds a tutorial how to setup the secureCodeBox to use an external persistence provider. The tutorial focuses on DefectDojo, but also contains a guide for ElasticSearch/Kibana.

2022-09-20 08:45 UTC, the-simmon commented
Im getting a 500 error in my browser when i bulk edit the findings. **Managing findings via the secureCodeBox and DefectDojo** step 2

2022-09-23 10:08 UTC, SebieF commented
> Im getting a 500 error in my browser when i bulk edit the findings (i used kind instead of minio but that should work as well). **Managing findings via the secureCodeBox and DefectDojo** step 2. Using the minikube step 2 works but the deduplication doesnt seem to function.

I added a troubleshooting section for server errors in DefectDojo and explicit kind instructions, hope it solves the issue :)

2022-09-28 09:46 UTC, malexmave requested changes
A few points as inline comments.

Additionally, one more thing: the DefectDojo hook will, by default, overwrite the findings with whatever it reads back from DefectDojo. Thus, if you run both DD and Elastic, the order of the hook execution matters. This can be done using the [hook order](https://www.securecodebox.io/docs/how-tos/hooks#hook-order) functionality. Or alternatively, by putting the DD hook in [read-only mode](https://www.securecodebox.io/docs/hooks/defectdojo#read-only-mode). Do you think that this needs to be added somewhere (maybe in the troubleshooting section), or is this arcane knowledge that is not required for a basic tutorial?

2022-09-28 09:46 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +and security orchestration. The *secureCodeBox* provides a hook that allows to directly connect the *scb* to a local
Isn't the common abbreviation we use SCB (uppercase)?

```suggestion
and security orchestration. The *secureCodeBox* provides a hook that allows to directly connect the *SCB* to a local
```

2022-09-28 09:46 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +</code>
This code snippet uses different syntax highlighting than the one above it. Can we somehow also set this to bash mode?

2022-09-28 09:46 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +[localhost:8080](http://localhost:8080). You should see the DefectDojo login mask.
Why are we forwarding `defectdojo.default.minikube.local` to localhost in /etc/hosts, but now using `localhost` in the instructions either way?

2022-09-28 09:46 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +After the scan has finished, you can view the findings in Kibana. Therefore, create a port-forward:
```suggestion
After the scan has finished, you can view the findings in Kibana. Create a port-forward:
```

2022-09-28 09:46 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +the createSecret* flags in the values.yaml file of DefectDojo must not be set.
```suggestion
the *createSecret* flags in the values.yaml file of DefectDojo must not be set. 
```

2022-09-28 10:12 UTC, SebieF commented on docs/how-tos/persistence-storage.md
> +</code>
Unfortunately I did not find a way to do this because it is in this summary html tag and the code tag does not react to any "class" attributes that I add..

2022-09-28 10:20 UTC, SebieF commented on docs/how-tos/persistence-storage.md
> +[localhost:8080](http://localhost:8080). You should see the DefectDojo login mask.
Good catch!

2022-09-28 10:32 UTC, SebieF commented
Thank you! I also added the part about using DD and ElasticSearch at the same time, I think a small paragraph at the end might do more good than harm :)

2022-09-28 10:34 UTC, malexmave requested changes
Seems like you accidentally left a placeholder in.

2022-09-28 10:34 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +Adding note for using DD and ElasticSearch
```suggestion

```

2022-09-28 10:36 UTC, malexmave commented on docs/how-tos/persistence-storage.md
> +</code>
Fair enough, was worth a try.

2022-09-28 10:50 UTC, malexmave approved these changes
Thanks, looks good to me!

2022-09-28 10:51 UTC, merged