Draft: Why scb v2
secureCodeBox/documentation pull request #48
Opened 2020-11-03 11:44 UTC by Weltraumschaf

Article about the architectureofv1 and why we changed to v2.

2021-06-04 09:55 UTC, rseedorff requested changes

2021-06-04 09:55 UTC, rseedorff commented on blog/2020-11-04-why-securecodebox-version-2.md
> +- but way simpler image because CLI args andparsing stuff is outside
typo "and parsing"

2021-06-04 09:55 UTC, rseedorff commented on blog/2020-11-04-why-securecodebox-version-2.md
> +- lurcher sidecar to collect data foranykind of scanner
sidecar (lurcher) to collect data for any kind of scanner

2021-06-04 09:55 UTC, rseedorff commented on blog/2020-11-04-why-securecodebox-version-2.md
> +- but total hard-coupling  to k8s
typo (spacing)

2021-06-04 09:55 UTC, rseedorff commented on blog/2020-11-04-why-securecodebox-version-2.md
> +- easy use of scanners in  cloud based projects
typo (spacing)

2021-06-07 09:55 UTC, Weltraumschaf commented
I messed up with my branches. Will open new PR.

2021-06-07 09:55 UTC, closed without merging