Add draft for architecture v2 article
secureCodeBox/documentation pull request #79
Opened 2021-05-21 15:31 UTC by Weltraumschaf

Signed-off-by: Sven Strittmatter <sven.strittmatter@iteratec.com>

2021-05-22 14:20 UTC, fuhrmeistery requested changes
Looks great. Just some minor spelling errors

2021-05-22 14:20 UTC, fuhrmeistery commented on blog/2021-05-21-the-architecture-of-securecodebox-v2.md
> +In [Kubernetes 1.17 a new concept of custom resources was introduces](https://medium.com/velotio-perspectives/extending-kubernetes-apis-with-custom-resource-definitions-crds-139c99ed3477). The short
Just fixing some spelling
```suggestion
In [Kubernetes 1.17 a new concept of custom resources was introduces](https://medium.com/velotio-perspectives/extending-kubernetes-apis-with-custom-resource-definitions-crds-139c99ed3477). The short idea is, that you may extend Kubernetes with your own resources additionally to the default ones shipped with Kubernetes. Why should you do this? The interesting part of Kubernetes is that it is a great tool for resource management. Solely it is the most important part of Kubernetes. In *version 1* we "abused" a BPMN engine for this work. But since the most important parts of the *secureCodeBox* (the *scanners*) are containers anyway, it makes sense to use a tool which is designed for handling such resources. So we came up with the idea to define the *scanners* as custom resources and replace the heavy *engine* from *version 1* with a custom [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for Kubernetes. This idea is based upon the master thesis our core maintainer [Jannik](https://github.com/J12934) has written about [Automatic Assessment of Applications Security Aspects running in Cloud Environments](https://files.hollenbach.dev/master-thesis-jannik-hollenbach.pdf). The following diagram shows the new architecture of *secureCodeBox version 2*.
```

2021-05-22 14:20 UTC, fuhrmeistery commented on blog/2021-05-21-the-architecture-of-securecodebox-v2.md
> +- but way simpler image because CLI args andparsing stuff is outside
```suggestion
- but way simpler image because CLI args and parsing stuff is outside
```

2021-05-22 14:20 UTC, fuhrmeistery commented on blog/2021-05-21-the-architecture-of-securecodebox-v2.md
> +- lurcher sidecar to collect data foranykind of scanner
```suggestion
- lurcher sidecar to collect data for any kind of scanner
```

2021-05-22 14:20 UTC, fuhrmeistery commented on blog/2021-05-21-the-architecture-of-securecodebox-v2.md
> +- but k8s is ubiquitious
```suggestion
- but k8s is ubiquitous
```

2021-05-22 14:20 UTC, fuhrmeistery commented on blog/2021-05-21-the-architecture-of-securecodebox-v2.md
> +- CLI first -> complete controlleable via kubectl
```suggestion
- CLI first -> complete controllable via kubectl
```

2021-05-25 08:46 UTC, fuhrmeistery approved these changes

2021-06-08 13:13 UTC, J12934 requested changes

2021-06-08 13:13 UTC, J12934 commented on blog/2021-06-12-the-architecture-of-securecodebox-v2.md
> +In [Kubernetes 1.17 a new concept of custom resources was introduces](https://medium.com/velotio-perspectives/extending-kubernetes-apis-with-custom-resource-definitions-crds-139c99ed3477). The short
1.7 not 1.17
```suggestion
In [Kubernetes 1.7 a new concept of custom resources was introduced](https://medium.com/velotio-perspectives/extending-kubernetes-apis-with-custom-resource-definitions-crds-139c99ed3477). The short idea is, that you may extend Kubernetes with your own resources in addition to the default ones shipped with Kubernetes. Why should you do this? The interesting part of Kubernetes is that it is a great tool for resource management. Solely it is the the most important part of Kubernetes. In *version 1* we "abused" a BPMN engine for this work. But since the most important parts of the *secureCodeBox* (the *scanners*) are containers anyway, it makes sense to use a tool which is designed for handling such resources. So we came up with the idea to define the *scanners* as custom resources and replace the heavy *engine* from *version 1* with a custom [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for Kubernetes. This idea is based upon the master thesis our core maintainer [Jannik](https://github.com/J12934) has written about [Automatic Assessment of Applications Security Aspects running in Cloud Environments](https://files.hollenbach.dev/master-thesis-jannik-hollenbach.pdf). The following diagram shows the new architecture of *secureCodeBox version 2*.
```

2021-06-29 12:08 UTC, Weltraumschaf commented on blog/2021-06-12-the-architecture-of-securecodebox-v2.md
> +In [Kubernetes 1.17 a new concept of custom resources was introduces](https://medium.com/velotio-perspectives/extending-kubernetes-apis-with-custom-resource-definitions-crds-139c99ed3477). The short
What is the concrete change here?

2021-07-02 09:26 UTC, Weltraumschaf commented
I've rewritten some of the text and squashed everything in one commit.

2021-07-06 09:59 UTC, fuhrmeistery approved these changes

2021-07-14 09:14 UTC, J12934 reviewed
This is a good recap of v1 and its challenges.

I think one of biggest weak points of the v1 is still missing from the Problems list.

The *scanners* in v1 were highly coupled to the BPMN models in the engine. That meant that to implement a new scanner you'd have to edit both the engine and create the new scanner microservice. So you'd basically have the worst of both worlds a monolith and a ton of microservices. This was made even worth by a lot of the other points you've listed, e.g. a scanner fix often required a coordinated patch release in both the engine and the scanner repo.

2021-07-14 19:33 UTC, rseedorff requested changes
Nice 👍🏻 Just some small findings...

2021-07-14 19:33 UTC, rseedorff commented on blog/2021-06-07-why-securecodebox-version-2.md
> +### Implementation oft the Scan Process Workflows
```suggestion
### Implementation of the Scan Process Workflows
```

2021-07-14 19:33 UTC, rseedorff commented on blog/2021-06-25-the-architecture-of-securecodebox-v2.md
> +But anyway you may want some web UI to manage your findings. At the moment we provide simply Grafana and Elastic to visualize them. But we're working hard on better solutions. Additionally you can im
```suggestion
But anyway you may want some web UI to manage your findings. At the moment we provide simply Kibana and Elasticsearch to visualize them. But we're working hard on better solutions. Additionally you can import all the findings in any system you want with a [custom *read hook*](/docs/architecture/adr/adr_0002).
```

2021-07-19 15:57 UTC, J12934 approved these changes

2021-07-22 14:02 UTC, merged